-- Auto-generated by scripts/export_sqlite_to_supabase_sql.py
-- Source: forge.db
BEGIN;
SET session_replication_role = replica;

DROP TABLE IF EXISTS "workout_exercises" CASCADE;
DROP TABLE IF EXISTS "split_workouts" CASCADE;
DROP TABLE IF EXISTS "Posts" CASCADE;
DROP TABLE IF EXISTS "Likes" CASCADE;
DROP TABLE IF EXISTS "Friends" CASCADE;
DROP TABLE IF EXISTS "Comments" CASCADE;
DROP TABLE IF EXISTS "meal_tags" CASCADE;
DROP TABLE IF EXISTS "meal_ingredients" CASCADE;
DROP TABLE IF EXISTS "meal_dietary_tags" CASCADE;
DROP TABLE IF EXISTS "exercise_tags" CASCADE;
DROP TABLE IF EXISTS "exercise_muscle_groups" CASCADE;
DROP TABLE IF EXISTS "Profiles" CASCADE;
DROP TABLE IF EXISTS "menu_meals" CASCADE;
DROP TABLE IF EXISTS "Workouts" CASCADE;
DROP TABLE IF EXISTS "Splits" CASCADE;
DROP TABLE IF EXISTS "SpiceLevelTags" CASCADE;
DROP TABLE IF EXISTS "PrepTimeTags" CASCADE;
DROP TABLE IF EXISTS "MuscleGroupTags" CASCADE;
DROP TABLE IF EXISTS "Meals" CASCADE;
DROP TABLE IF EXISTS "Machines" CASCADE;
DROP TABLE IF EXISTS "Ingredients" CASCADE;
DROP TABLE IF EXISTS "GoalTags" CASCADE;
DROP TABLE IF EXISTS "Exercises" CASCADE;
DROP TABLE IF EXISTS "ExerciseTypeTags" CASCADE;
DROP TABLE IF EXISTS "DifficultyTags" CASCADE;
DROP TABLE IF EXISTS "DietaryTags" CASCADE;
DROP TABLE IF EXISTS "CuisineTags" CASCADE;
DROP TABLE IF EXISTS "CookTimeTags" CASCADE;
DROP TABLE IF EXISTS "ComplexityTags" CASCADE;
DROP TABLE IF EXISTS "Accounts" CASCADE;


CREATE TABLE "Accounts" (
	"UserID" SERIAL NOT NULL, 
	email TEXT NOT NULL, 
	username TEXT NOT NULL, 
	password_hash TEXT NOT NULL, 
	bio TEXT, 
	refresh_token_hash TEXT, 
	refresh_expires_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY ("UserID"), 
	UNIQUE (email), 
	UNIQUE (username)
);


CREATE TABLE "ComplexityTags" (
	"ComplexityID" SERIAL NOT NULL, 
	name TEXT NOT NULL, 
	PRIMARY KEY ("ComplexityID"), 
	UNIQUE (name)
);


CREATE TABLE "CookTimeTags" (
	"CookTimeID" SERIAL NOT NULL, 
	name TEXT NOT NULL, 
	PRIMARY KEY ("CookTimeID"), 
	UNIQUE (name)
);


CREATE TABLE "CuisineTags" (
	"CuisineID" SERIAL NOT NULL, 
	name TEXT NOT NULL, 
	PRIMARY KEY ("CuisineID"), 
	UNIQUE (name)
);


CREATE TABLE "DietaryTags" (
	"DietaryID" SERIAL NOT NULL, 
	name TEXT NOT NULL, 
	PRIMARY KEY ("DietaryID"), 
	UNIQUE (name)
);


CREATE TABLE "DifficultyTags" (
	"DifficultyID" SERIAL NOT NULL, 
	name TEXT NOT NULL, 
	PRIMARY KEY ("DifficultyID"), 
	UNIQUE (name)
);


CREATE TABLE "ExerciseTypeTags" (
	"ExerciseTypeID" SERIAL NOT NULL, 
	name TEXT NOT NULL, 
	PRIMARY KEY ("ExerciseTypeID"), 
	UNIQUE (name)
);


CREATE TABLE "Exercises" (
	"ExerciseID" SERIAL NOT NULL, 
	name TEXT NOT NULL, 
	PRIMARY KEY ("ExerciseID")
);


CREATE TABLE "GoalTags" (
	"GoalID" SERIAL NOT NULL, 
	name TEXT NOT NULL, 
	PRIMARY KEY ("GoalID"), 
	UNIQUE (name)
);


CREATE TABLE "Ingredients" (
	"IngredientID" SERIAL NOT NULL, 
	name TEXT NOT NULL, 
	PRIMARY KEY ("IngredientID")
);


CREATE TABLE "Machines" (
	"MachineID" SERIAL NOT NULL, 
	name TEXT NOT NULL, 
	PRIMARY KEY ("MachineID")
);


CREATE TABLE "Meals" (
	"MealID" SERIAL NOT NULL, 
	name TEXT NOT NULL, 
	PRIMARY KEY ("MealID")
);


CREATE TABLE "MuscleGroupTags" (
	"MuscleGroupID" SERIAL NOT NULL, 
	name TEXT NOT NULL, 
	PRIMARY KEY ("MuscleGroupID"), 
	UNIQUE (name)
);


CREATE TABLE "PrepTimeTags" (
	"PrepTimeID" SERIAL NOT NULL, 
	name TEXT NOT NULL, 
	PRIMARY KEY ("PrepTimeID"), 
	UNIQUE (name)
);


CREATE TABLE "SpiceLevelTags" (
	"SpiceLevelID" SERIAL NOT NULL, 
	name TEXT NOT NULL, 
	PRIMARY KEY ("SpiceLevelID"), 
	UNIQUE (name)
);


CREATE TABLE "Splits" (
	"SplitID" SERIAL NOT NULL, 
	name TEXT NOT NULL, 
	PRIMARY KEY ("SplitID")
);


CREATE TABLE "Workouts" (
	"WorkoutID" SERIAL NOT NULL, 
	name TEXT NOT NULL, 
	PRIMARY KEY ("WorkoutID")
);


CREATE TABLE menu_meals (
	"MenuMealID" SERIAL NOT NULL, 
	restaurant TEXT NOT NULL, 
	category TEXT NOT NULL, 
	product TEXT NOT NULL, 
	serving_size FLOAT, 
	energy_kcal FLOAT, 
	carbohydrates_g FLOAT, 
	protein_g FLOAT, 
	fiber_g FLOAT, 
	sugar_g FLOAT, 
	total_fat_g FLOAT, 
	saturated_fat_g FLOAT, 
	trans_fat_g FLOAT, 
	cholesterol_mg FLOAT, 
	sodium_mg FLOAT, 
	PRIMARY KEY ("MenuMealID")
);


CREATE TABLE "Profiles" (
	"ProfileID" INTEGER NOT NULL, 
	age INTEGER NOT NULL, 
	weight INTEGER NOT NULL, 
	height_in INTEGER NOT NULL, 
	gender TEXT NOT NULL, 
	health_status TEXT, 
	health_goals TEXT, 
	PRIMARY KEY ("ProfileID"), 
	FOREIGN KEY("ProfileID") REFERENCES "Accounts" ("UserID")
);


CREATE TABLE exercise_muscle_groups (
	"ExerciseID" INTEGER NOT NULL, 
	"MuscleGroupID" INTEGER NOT NULL, 
	PRIMARY KEY ("ExerciseID", "MuscleGroupID"), 
	FOREIGN KEY("ExerciseID") REFERENCES "Exercises" ("ExerciseID"), 
	FOREIGN KEY("MuscleGroupID") REFERENCES "MuscleGroupTags" ("MuscleGroupID")
);


CREATE TABLE exercise_tags (
	"ExerciseID" INTEGER NOT NULL, 
	"DifficultyID" INTEGER NOT NULL, 
	"ExerciseTypeID" INTEGER NOT NULL, 
	PRIMARY KEY ("ExerciseID"), 
	FOREIGN KEY("ExerciseID") REFERENCES "Exercises" ("ExerciseID"), 
	FOREIGN KEY("DifficultyID") REFERENCES "DifficultyTags" ("DifficultyID"), 
	FOREIGN KEY("ExerciseTypeID") REFERENCES "ExerciseTypeTags" ("ExerciseTypeID")
);


CREATE TABLE meal_dietary_tags (
	"MealID" INTEGER NOT NULL, 
	"DietaryID" INTEGER NOT NULL, 
	PRIMARY KEY ("MealID", "DietaryID"), 
	FOREIGN KEY("MealID") REFERENCES "Meals" ("MealID"), 
	FOREIGN KEY("DietaryID") REFERENCES "DietaryTags" ("DietaryID")
);


CREATE TABLE meal_ingredients (
	"MealID" INTEGER NOT NULL, 
	"IngredientID" INTEGER NOT NULL, 
	serving_size FLOAT, 
	instructions TEXT, 
	PRIMARY KEY ("MealID", "IngredientID"), 
	FOREIGN KEY("MealID") REFERENCES "Meals" ("MealID"), 
	FOREIGN KEY("IngredientID") REFERENCES "Ingredients" ("IngredientID")
);


CREATE TABLE meal_tags (
	"MealID" INTEGER NOT NULL, 
	"SpiceLevelID" INTEGER NOT NULL, 
	"CuisineID" INTEGER NOT NULL, 
	"ComplexityID" INTEGER NOT NULL, 
	"GoalID" INTEGER NOT NULL, 
	"PrepTimeID" INTEGER NOT NULL, 
	"CookTimeID" INTEGER NOT NULL, 
	PRIMARY KEY ("MealID"), 
	FOREIGN KEY("MealID") REFERENCES "Meals" ("MealID"), 
	FOREIGN KEY("SpiceLevelID") REFERENCES "SpiceLevelTags" ("SpiceLevelID"), 
	FOREIGN KEY("CuisineID") REFERENCES "CuisineTags" ("CuisineID"), 
	FOREIGN KEY("ComplexityID") REFERENCES "ComplexityTags" ("ComplexityID"), 
	FOREIGN KEY("GoalID") REFERENCES "GoalTags" ("GoalID"), 
	FOREIGN KEY("PrepTimeID") REFERENCES "PrepTimeTags" ("PrepTimeID"), 
	FOREIGN KEY("CookTimeID") REFERENCES "CookTimeTags" ("CookTimeID")
);


CREATE TABLE "Comments" (
	"PostID" INTEGER NOT NULL, 
	"ProfileID" INTEGER NOT NULL, 
	text TEXT NOT NULL, 
	PRIMARY KEY ("PostID", "ProfileID"), 
	FOREIGN KEY("ProfileID") REFERENCES "Profiles" ("ProfileID")
);


CREATE TABLE "Friends" (
	"ProfileID1" INTEGER NOT NULL, 
	"ProfileID2" INTEGER NOT NULL, 
	PRIMARY KEY ("ProfileID1", "ProfileID2"), 
	FOREIGN KEY("ProfileID1") REFERENCES "Profiles" ("ProfileID"), 
	FOREIGN KEY("ProfileID2") REFERENCES "Profiles" ("ProfileID")
);


CREATE TABLE "Likes" (
	"PostID" INTEGER NOT NULL, 
	"ProfileID" INTEGER NOT NULL, 
	PRIMARY KEY ("PostID", "ProfileID"), 
	FOREIGN KEY("ProfileID") REFERENCES "Profiles" ("ProfileID")
);


CREATE TABLE "Posts" (
	"PostID" SERIAL NOT NULL, 
	"ProfileID" INTEGER NOT NULL, 
	"ExerciseID" INTEGER NOT NULL, 
	"WorkoutID" INTEGER NOT NULL, 
	"MachineID" INTEGER NOT NULL, 
	caption TEXT, 
	PRIMARY KEY ("PostID"), 
	FOREIGN KEY("ProfileID") REFERENCES "Profiles" ("ProfileID"), 
	FOREIGN KEY("ExerciseID") REFERENCES "Exercises" ("ExerciseID"), 
	FOREIGN KEY("WorkoutID") REFERENCES "Workouts" ("WorkoutID"), 
	FOREIGN KEY("MachineID") REFERENCES "Machines" ("MachineID")
);


CREATE TABLE split_workouts (
	"SplitID" INTEGER NOT NULL, 
	"WorkoutID" INTEGER NOT NULL, 
	"ProfileID" INTEGER NOT NULL, 
	day INTEGER, 
	period INTEGER, 
	notes TEXT, 
	PRIMARY KEY ("SplitID", "WorkoutID", "ProfileID"), 
	FOREIGN KEY("SplitID") REFERENCES "Splits" ("SplitID"), 
	FOREIGN KEY("WorkoutID") REFERENCES "Workouts" ("WorkoutID"), 
	FOREIGN KEY("ProfileID") REFERENCES "Profiles" ("ProfileID")
);


CREATE TABLE workout_exercises (
	"WorkoutID" INTEGER NOT NULL, 
	"ExerciseID" INTEGER NOT NULL, 
	"MachineID" INTEGER NOT NULL, 
	"ProfileID" INTEGER NOT NULL, 
	sets INTEGER, 
	reps INTEGER, 
	weight INTEGER, 
	notes TEXT, 
	PRIMARY KEY ("WorkoutID", "ExerciseID", "MachineID", "ProfileID"), 
	FOREIGN KEY("WorkoutID") REFERENCES "Workouts" ("WorkoutID"), 
	FOREIGN KEY("ExerciseID") REFERENCES "Exercises" ("ExerciseID"), 
	FOREIGN KEY("MachineID") REFERENCES "Machines" ("MachineID"), 
	FOREIGN KEY("ProfileID") REFERENCES "Profiles" ("ProfileID")
);

-- Data for "Accounts" (1 rows)
INSERT INTO "Accounts" ("UserID", "email", "username", "password_hash", "bio", "refresh_token_hash", "refresh_expires_at") VALUES (1, 'demo@forge.app', 'demo_user', 'demo_hash', 'Demo profile', NULL, NULL);

-- Data for "Exercises" (2 rows)
INSERT INTO "Exercises" ("ExerciseID", "name") VALUES (1, 'Bench Press');
INSERT INTO "Exercises" ("ExerciseID", "name") VALUES (2, 'Lat Pulldown');

-- Data for "Machines" (2 rows)
INSERT INTO "Machines" ("MachineID", "name") VALUES (1, 'dumbbell');
INSERT INTO "Machines" ("MachineID", "name") VALUES (2, 'lat pulldown');

-- Data for "Workouts" (11 rows)
INSERT INTO "Workouts" ("WorkoutID", "name") VALUES (1, 'Chest Demo');
INSERT INTO "Workouts" ("WorkoutID", "name") VALUES (2, 'Back Demo');
INSERT INTO "Workouts" ("WorkoutID", "name") VALUES (3, 'Chest Demo 2026-03-05 23:09');
INSERT INTO "Workouts" ("WorkoutID", "name") VALUES (4, 'Chest Demo 2026-03-05 23:14');
INSERT INTO "Workouts" ("WorkoutID", "name") VALUES (5, 'Chest Demo (Edited) 2026-03-05 23:14');
INSERT INTO "Workouts" ("WorkoutID", "name") VALUES (6, 'Chest Demo (Edited) 2026-03-05 23:15');
INSERT INTO "Workouts" ("WorkoutID", "name") VALUES (7, 'Chest Demo (Edited) 2026-03-05 23:15 2026-03-05 23:21');
INSERT INTO "Workouts" ("WorkoutID", "name") VALUES (8, 'Chest Demo (Edited) 2026-03-05 23:15 2026-03-05 23:21 2026-03-05 23:24');
INSERT INTO "Workouts" ("WorkoutID", "name") VALUES (9, 'Chest Demo (Edited) 2026-03-05 23:15 2026-03-05 23:21 2026-03-05 23:24 2026-03-05 23:26');
INSERT INTO "Workouts" ("WorkoutID", "name") VALUES (10, 'Chest Demo 2026-03-05 23:09 2026-03-05 23:41');
INSERT INTO "Workouts" ("WorkoutID", "name") VALUES (11, 'Chest Demo (Edited) 2026-03-06 00:08');

-- Data for "Profiles" (1 rows)
INSERT INTO "Profiles" ("ProfileID", "age", "weight", "height_in", "gender", "health_status", "health_goals") VALUES (1, 24, 175, 70, 'N/A', 'good', 'build strength');

-- Data for "workout_exercises" (2 rows)
INSERT INTO "workout_exercises" ("WorkoutID", "ExerciseID", "MachineID", "ProfileID", "sets", "reps", "weight", "notes") VALUES (1, 1, 1, 1, 4, 10, 135, 'sample log row 1');
INSERT INTO "workout_exercises" ("WorkoutID", "ExerciseID", "MachineID", "ProfileID", "sets", "reps", "weight", "notes") VALUES (2, 2, 2, 1, 3, 12, 120, 'sample log row 2');

-- Reset sequences
SELECT setval(pg_get_serial_sequence('"Accounts"', 'UserID'), COALESCE((SELECT MAX("UserID") FROM "Accounts"), 1), (SELECT COUNT(*) > 0 FROM "Accounts"));
SELECT setval(pg_get_serial_sequence('"ComplexityTags"', 'ComplexityID'), COALESCE((SELECT MAX("ComplexityID") FROM "ComplexityTags"), 1), (SELECT COUNT(*) > 0 FROM "ComplexityTags"));
SELECT setval(pg_get_serial_sequence('"CookTimeTags"', 'CookTimeID'), COALESCE((SELECT MAX("CookTimeID") FROM "CookTimeTags"), 1), (SELECT COUNT(*) > 0 FROM "CookTimeTags"));
SELECT setval(pg_get_serial_sequence('"CuisineTags"', 'CuisineID'), COALESCE((SELECT MAX("CuisineID") FROM "CuisineTags"), 1), (SELECT COUNT(*) > 0 FROM "CuisineTags"));
SELECT setval(pg_get_serial_sequence('"DietaryTags"', 'DietaryID'), COALESCE((SELECT MAX("DietaryID") FROM "DietaryTags"), 1), (SELECT COUNT(*) > 0 FROM "DietaryTags"));
SELECT setval(pg_get_serial_sequence('"DifficultyTags"', 'DifficultyID'), COALESCE((SELECT MAX("DifficultyID") FROM "DifficultyTags"), 1), (SELECT COUNT(*) > 0 FROM "DifficultyTags"));
SELECT setval(pg_get_serial_sequence('"ExerciseTypeTags"', 'ExerciseTypeID'), COALESCE((SELECT MAX("ExerciseTypeID") FROM "ExerciseTypeTags"), 1), (SELECT COUNT(*) > 0 FROM "ExerciseTypeTags"));
SELECT setval(pg_get_serial_sequence('"Exercises"', 'ExerciseID'), COALESCE((SELECT MAX("ExerciseID") FROM "Exercises"), 1), (SELECT COUNT(*) > 0 FROM "Exercises"));
SELECT setval(pg_get_serial_sequence('"GoalTags"', 'GoalID'), COALESCE((SELECT MAX("GoalID") FROM "GoalTags"), 1), (SELECT COUNT(*) > 0 FROM "GoalTags"));
SELECT setval(pg_get_serial_sequence('"Ingredients"', 'IngredientID'), COALESCE((SELECT MAX("IngredientID") FROM "Ingredients"), 1), (SELECT COUNT(*) > 0 FROM "Ingredients"));
SELECT setval(pg_get_serial_sequence('"Machines"', 'MachineID'), COALESCE((SELECT MAX("MachineID") FROM "Machines"), 1), (SELECT COUNT(*) > 0 FROM "Machines"));
SELECT setval(pg_get_serial_sequence('"Meals"', 'MealID'), COALESCE((SELECT MAX("MealID") FROM "Meals"), 1), (SELECT COUNT(*) > 0 FROM "Meals"));
SELECT setval(pg_get_serial_sequence('"MuscleGroupTags"', 'MuscleGroupID'), COALESCE((SELECT MAX("MuscleGroupID") FROM "MuscleGroupTags"), 1), (SELECT COUNT(*) > 0 FROM "MuscleGroupTags"));
SELECT setval(pg_get_serial_sequence('"PrepTimeTags"', 'PrepTimeID'), COALESCE((SELECT MAX("PrepTimeID") FROM "PrepTimeTags"), 1), (SELECT COUNT(*) > 0 FROM "PrepTimeTags"));
SELECT setval(pg_get_serial_sequence('"SpiceLevelTags"', 'SpiceLevelID'), COALESCE((SELECT MAX("SpiceLevelID") FROM "SpiceLevelTags"), 1), (SELECT COUNT(*) > 0 FROM "SpiceLevelTags"));
SELECT setval(pg_get_serial_sequence('"Splits"', 'SplitID'), COALESCE((SELECT MAX("SplitID") FROM "Splits"), 1), (SELECT COUNT(*) > 0 FROM "Splits"));
SELECT setval(pg_get_serial_sequence('"Workouts"', 'WorkoutID'), COALESCE((SELECT MAX("WorkoutID") FROM "Workouts"), 1), (SELECT COUNT(*) > 0 FROM "Workouts"));
SELECT setval(pg_get_serial_sequence('"menu_meals"', 'MenuMealID'), COALESCE((SELECT MAX("MenuMealID") FROM "menu_meals"), 1), (SELECT COUNT(*) > 0 FROM "menu_meals"));
SELECT setval(pg_get_serial_sequence('"Profiles"', 'ProfileID'), COALESCE((SELECT MAX("ProfileID") FROM "Profiles"), 1), (SELECT COUNT(*) > 0 FROM "Profiles"));
SELECT setval(pg_get_serial_sequence('"exercise_tags"', 'ExerciseID'), COALESCE((SELECT MAX("ExerciseID") FROM "exercise_tags"), 1), (SELECT COUNT(*) > 0 FROM "exercise_tags"));
SELECT setval(pg_get_serial_sequence('"meal_tags"', 'MealID'), COALESCE((SELECT MAX("MealID") FROM "meal_tags"), 1), (SELECT COUNT(*) > 0 FROM "meal_tags"));
SELECT setval(pg_get_serial_sequence('"Posts"', 'PostID'), COALESCE((SELECT MAX("PostID") FROM "Posts"), 1), (SELECT COUNT(*) > 0 FROM "Posts"));

SET session_replication_role = DEFAULT;
COMMIT;
