#!/usr/bin/env python3
"""
Generate a PostgreSQL-compatible migration SQL file from local forge.db.

Usage:
  python3 scripts/export_sqlite_to_supabase_sql.py \
    --sqlite forge.db \
    --out docs/migrations/supabase_forge_migration.sql
"""

from __future__ import annotations

import argparse
import datetime as dt
import sqlite3
from pathlib import Path
from typing import Any
import sys

from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateTable

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app.core.db import Base


def sql_literal(value: Any) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, (dt.datetime, dt.date)):
        return f"'{value.isoformat()}'"
    text = str(value).replace("'", "''")
    return f"'{text}'"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--sqlite", default="forge.db")
    parser.add_argument("--out", default="docs/migrations/supabase_forge_migration.sql")
    args = parser.parse_args()

    sqlite_path = Path(args.sqlite)
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    if not sqlite_path.exists():
        raise SystemExit(f"SQLite DB not found: {sqlite_path}")

    conn = sqlite3.connect(str(sqlite_path))
    conn.row_factory = sqlite3.Row

    lines: list[str] = []
    lines.append("-- Auto-generated by scripts/export_sqlite_to_supabase_sql.py")
    lines.append("-- Source: forge.db")
    lines.append("BEGIN;")
    lines.append("SET session_replication_role = replica;")
    lines.append("")

    # Drop all app tables first, then recreate from SQLAlchemy metadata for PostgreSQL.
    for table in reversed(Base.metadata.sorted_tables):
        lines.append(f'DROP TABLE IF EXISTS "{table.name}" CASCADE;')
    lines.append("")

    pg_dialect = postgresql.dialect()
    for table in Base.metadata.sorted_tables:
        ddl = str(CreateTable(table).compile(dialect=pg_dialect)).rstrip()
        lines.append(f"{ddl};")
        lines.append("")

    table_counts: list[tuple[str, int]] = []
    for table in Base.metadata.sorted_tables:
        table_name = table.name
        cols = [c.name for c in table.columns]
        col_sql = ", ".join([f'"{c}"' for c in cols])

        rows = conn.execute(f'SELECT * FROM "{table_name}"').fetchall()
        table_counts.append((table_name, len(rows)))
        if not rows:
            continue

        lines.append(f'-- Data for "{table_name}" ({len(rows)} rows)')
        for row in rows:
            values = ", ".join(sql_literal(row[c]) for c in cols)
            lines.append(f'INSERT INTO "{table_name}" ({col_sql}) VALUES ({values});')
        lines.append("")

    # Reset serial sequences after explicit PK inserts.
    lines.append("-- Reset sequences")
    for table in Base.metadata.sorted_tables:
        pk_cols = list(table.primary_key.columns)
        if len(pk_cols) != 1:
            continue
        pk = pk_cols[0]
        if pk.type.__class__.__name__.lower() not in {"integer", "biginteger", "smallinteger"}:
            continue
        lines.append(
            f"SELECT setval("
            f"pg_get_serial_sequence('\"{table.name}\"', '{pk.name}'), "
            f"COALESCE((SELECT MAX(\"{pk.name}\") FROM \"{table.name}\"), 1), "
            f"(SELECT COUNT(*) > 0 FROM \"{table.name}\")"
            f");"
        )

    lines.append("")
    lines.append("SET session_replication_role = DEFAULT;")
    lines.append("COMMIT;")
    lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")

    print(f"Wrote SQL migration: {out_path}")
    print("Row counts in source SQLite:")
    for name, count in table_counts:
        print(f"- {name}: {count}")


if __name__ == "__main__":
    main()
