import { StyleSheet } from "react-native"

export const styles = StyleSheet.create({
  scrollContent: { flexGrow: 1 },
  container: { flex: 1, padding: 16 },
  pageTitle: { fontSize: 22, fontWeight: "800", marginBottom: 12 },
  sectionHeader: {
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 1.2,
    textTransform: "uppercase",
    opacity: 0.45,
    marginTop: 28,
    marginBottom: 6,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(0,0,0,0.15)",
    paddingBottom: 6,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    marginTop: 14,
    marginBottom: 6,
  },
  accountSubsectionTitle: {
    fontSize: 15,
    fontWeight: "800",
    marginTop: 18,
    marginBottom: 8,
    opacity: 0.9,
  },
  helper: { opacity: 0.65, fontSize: 13, marginBottom: 4 },
  modeRow: { flexDirection: "row", gap: 10, marginTop: 6, flexWrap: "wrap" },
  modeBtn: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(0,0,0,0.25)",
  },
  modeBtnSelected: { backgroundColor: "#2f80ed", borderColor: "#2f80ed" },
  modeBtnText: { fontWeight: "700" },
  modeBtnTextSelected: { color: "white" },
  previewCard: {
    marginTop: 14,
    padding: 14,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(0,0,0,0.2)",
  },
  footerNote: { marginTop: 14, opacity: 0.55, fontSize: 12 },
  statusBanner: {
    padding: 12,
    borderRadius: 10,
    marginBottom: 12,
  },
  statusOk: { backgroundColor: "#d4edda" },
  statusErr: { backgroundColor: "#f8d7da" },
  statusText: { fontWeight: "600", fontSize: 13 },
  fieldWrapper: { marginBottom: 10 },
  fieldLabel: {
    fontSize: 13,
    fontWeight: "600",
    marginBottom: 4,
    opacity: 0.75,
  },
  input: {
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 9,
    fontSize: 15,
  },
  inputMultiline: { minHeight: 72, textAlignVertical: "top" },
  btn: {
    paddingHorizontal: 16,
    paddingVertical: 11,
    borderRadius: 10,
    alignItems: "center",
    marginTop: 6,
    alignSelf: "flex-start",
  },
  btnPrimary: { backgroundColor: "#2f80ed" },
  btnSecondary: {
    backgroundColor: "transparent",
    borderWidth: StyleSheet.hairlineWidth,
  },
  btnDanger: { backgroundColor: "#e53935" },
  btnDisabled: { opacity: 0.45 },
  btnText: { color: "white", fontWeight: "700", fontSize: 14 },
  notificationCard: {
    marginTop: 10,
    padding: 14,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(0,0,0,0.15)",
    backgroundColor: "rgba(47,128,237,0.04)",
    gap: 12,
  },
  timeRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  timeLabel: {
    fontSize: 15,
    fontWeight: "700",
  },
  timeValue: {
    marginTop: 2,
    fontSize: 13,
    opacity: 0.7,
  },
  timeButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: "#2f80ed",
  },
  timeButtonText: {
    color: "white",
    fontWeight: "700",
  },
  pickerCard: {
    marginTop: 8,
    paddingTop: 4,
  },

  accountNested: {
    marginLeft: 12,
    paddingLeft: 14,
    borderLeftWidth: 2,
    borderLeftColor: "rgba(0,0,0,0.12)",
  },

  accountSubsection: {
    marginTop: 18,
  },

  dropdown: {
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: "#ffffff",
  },
});
